#!/bin/bash
. /usr/local/bin/common

height="$(($(tput lines) - 6))"
width="$(($(tput cols) - 20))"

tput civis
while true; do
    ITEMS=(
        1 'checkra1n'
        2 'checkra1n (A9X)'
        3 'odysseyra1n'
        4 'ssh'
        5 'Shell'
        6 'Shutdown'
        7 'Reboot'
    )
    ITEMS_COUNT=$((${#ITEMS[@]}/2))
    SELECTION=$(dialog \
        --colors --no-cancel --title 'sh0wer' --menu '' \
        $height $width $ITEMS_COUNT "${ITEMS[@]}" 3>&1 1>&2 2>&3 3>&-)
    case "$SELECTION" in
    1) 
        clear
        tput cnorm
        /usr/local/bin/checkra1n
        ;;
    2)
        clear
        tput cnorm
        /usr/local/bin/checkra1n -k /opt/a9x/PongoConsolidated.bin
        ;;
    3)
        clear
        tput cnorm
        /usr/local/bin/odysseyra1n
        ;;
    4)
        clear
        tput cnorm
        /usr/local/bin/ssh_ios
        ;;
    5)
        clear
        tput cnorm
        echo "Go back to the menu by running 'menu'."
        break
        ;;
    6)
        clear
        sh0wer_logo
        sleep 2
        /usr/sbin/halt -p
        ;;
    7) 
        clear
        sh0wer_logo
        sleep 2
        /usr/sbin/halt --reboot
        ;;
    esac
done